[project]
name = "report-extract-poc"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "wilstein91", email = "williamus91@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "openpyxl>=3.1.5",
]

[project.scripts]
report-extract-poc = "report_extract_poc:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
